#注意，如果是在记事本上编写，下面的缩进不要使用Tab来缩进，不然会报错
spring:
  profiles:
    active: dev   #激活开发环境配置

---
server:
  port: 4001
spring:
  profiles: dev #开发环境
  application:
    name:cloud-config-dev
---
server:
  port: 4002 #端口号
spring:
  profiles: prod
  application:
    name:cloud-config-prod